SELECT
	kb_values.code,
	kb_values.trading_date
	kb_values.adjclose,
	kb_values.close,
	kb_values.high,
	kb_values.low,
	kb_values.open,
	kb_values.volume,
	kb_market.trading_date,
	kb_market.nikkei225,
	kb_market.topix,
	kb_market.jpxni400,
	kb_market.prime,
	kb_market.standard,
	kb_market.growth,
	kb_market.old_tosho,
	kb_market.growth_core,
	kb_market.mothers,
	kb_market.nikkei_vi,
	kb_market.reit,
	kb_market.dow,
	kb_market.nasdaq,
	kb_market.sp500,
	kb_market.gbr_ft,
	kb_market.fra_cac,
	kb_market.ger_dax,
	kb_market.rus_rts,
	kb_market.bra_bvsp,
	kb_market.ind_sensex,
	kb_market.hkg_han,
	kb_market.hkg_han_h,
	kb_market.hkg_red,
	kb_market.shanghai,
	kb_market.shanghai_a,
	kb_market.Shang_hongkong,
	kb_market.csi300,
	kb_market.singapore_st,
	kb_market.thailand_set,
	kb_market.kualalumpur,
	kb_market.Jakarta,
	kb_market.nikkei225_futures,
	kb_market.cme_futures,
	kb_market.sgx_futures,
	kb_market.mothers_futures,
	kb_market.nikkei400_futures,
	kb_market.jpn_bonds_futures,
	kb_market.jpn_bonds_futures_lev,
	kb_market.jpn_bonds_futures_In,
	kb_market.jpn_bonds_futures_Inw,
	kb_market.twn_futures,
	kb_market.chn_futures,
	kb_market.emini500,
	kb_market.emini400,
	kb_market.emini600,
	kb_market.emini_nasdaq,
	kb_market.emini_Dow,
	kb_market.emini_nikkei225,
	kb_market.sgx50,
	kb_market.usd_jpy_buy,
	kb_market.eur_jpy_buy,
	kb_market.aud_jpy_buy,
	kb_market.nzd_jpy_buy,
	kb_market.cad_jpy_buy,
	kb_market.chf_jpy_buy,
	kb_market.hkd_jpy_buy,
	kb_market.gbp_jpy_buy,
	kb_market.try_jpy_buy,
	kb_market.zar_jpy_buy,
	kb_market.rub_jpy_buy,
	kb_market.krw_jpy_buy,
	kb_market.mxn_jpy_buy,
	kb_market.brl_jpy_buy,
	kb_market.inr_jpy_buy,
	kb_market.cny_jpy_buy,
	kb_market.sgd_jpy_buy,
	kb_market.thb_jpy_buy,
	kb_market.myr_jpy_buy,
	kb_market.idr_jpy_buy,
	kb_market.usd_jpy_sell,
	kb_market.eur_jpy_sell,
	kb_market.aud_jpy_sell,
	kb_market.nzd_jpy_sell,
	kb_market.cad_jpy_sell,
	kb_market.chf_jpy_sell,
	kb_market.hkd_jpy_sell,
	kb_market.gbp_jpy_sell,
	kb_market.try_jpy_sell,
	kb_market.zar_jpy_sell,
	kb_market.rub_jpy_sell,
	kb_market.krw_jpy_sell,
	kb_market.mxn_jpy_sell,
	kb_market.brl_jpy_sell,
	kb_market.inr_jpy_sell,
	kb_market.cny_jpy_sell,
	kb_market.sgd_jpy_sell,
	kb_market.thb_jpy_sell,
	kb_market.myr_jpy_sell,
	kb_market.idr_jpy_sell,
	kb_market.oll_futures,
	kb_market.gas_futures,
	kb_market.gold_buy,
	kb_market.gold_sell,
	kb_market.gold_futures,
	kb_market.platinum_futures,
	kb_market.silver_futures,
	kb_market.copper_futures,
	kb_market.corn_futures,
	kb_market.wheat_futures,
	kb_market.soybeans_futures,
	kb_market.jpn_bonds_3y,
	kb_market.jpn_bonds_5y,
	kb_market.jpn_bonds_10y,
	kb_market.usa_bonds_5y,
	kb_market.usa_bonds_10y,
	kb_market.ger_bonds_10y,
	kb_market.eng_bonds_10y,
	kb_market.Fra_bonds_10y,
	kb_market.esp_bonds_10y,
	kb_market.por_bonds_10y,
	kb_market.eur_bonds_10y,
	kb_market.ita_bonds_10y,
	kb_market.grc_bonds_10y,
	kb_market.hun_bonds_10y,
	kb_market.jpn_call,
	kb_market.official_discount_rate,
	kb_market.usa_inter_rate,
	kb_market.can_inter_rate,
	kb_market.eur_inter_rate,
	kb_market.gbr_inter_rate,
	kb_market.she_inter_rate,
	kb_market.zaf_inter_rate,
	kb_market.hkg_inter_rate,
	kb_market.aus_inter_rate,
	kb_market.nzl_inter_rate,
	kb_market.ind_inter_rate,
	kb_market.chn_inter_rate,
	kb_market.bra_inter_rate,
	kb_market.rus_inter_rate,
	kb_market.tur_inter_rate,
	kb_market.mex_inter_rate,
	kb_finance.code,
	kb_finance.trading_date,
	kb_finance.fiscal_year,
	kb_finance.total_assets,
	kb_finance.net_assets,
	kb_finance.shareholders_equity,
	kb_finance.retained_earnings,
	kb_finance.loans_payable_short,
	kb_finance.loans_payable_long,
	kb_finance.bps,
	kb_finance.capital_ratio,
	kb_finance.cf_from_operating,
	kb_finance.cf_from_investment,
	kb_finance.cf_from_financial,
	kb_finance.capital_spending,
	kb_finance.cash_equivalents,
	kb_finance.cf_operating_margin,
	kb_finance.sales,
	kb_finance.operating_income,
	kb_finance.ordinary_income,
	kb_finance.net_income,
	kb_finance.eps,
	kb_finance.roe,
	kb_finance.roa,
	kb_finance.dividends,
	kb_finance.dividend_of_surplus,
	kb_finance.stock_buybacks,
	kb_finance.dpr,
	kb_finance.tpr,
	kb_finance.doe,	
	kb_idnr4.idnr4,
	kb_turtleb.tsplb,
	kb_turtles.tspls,
	kb_pin80b.pin80b,
	kb_pin80s.pin80s
FROM (((((((
	kb_values
INNER JOIN
	kb_market
ON
	kb_values.code = kb_market.code,
	kb_values.trading_date = kb_market.trading_date
)
INNER JOIN
	kb_finance
ON
	kb_values.code = kb_finance.code,
	kb_values.trading_date = kb_finance.trading_date
)
LEFT JOIN
	kb_idnr4
ON
	kb_values.code = kb_idnr4.code,
	kb_values.trading_date = kb_idnr4.trading_date
)
LEFT JOIN
	kb_turtleb
ON
	kb_values.code = kb_turtleb.code,
	kb_values.trading_date = kb_turtleb.trading_date
)
LEFT JOIN
	kb_turtles
ON
	kb_values.code = kb_turtles.code,
	kb_values.trading_date = kb_turtles.trading_date
)
LEFT JOIN
	kb_pin80b
ON
	kb_values.code = kb_pin80b.code,
	kb_values.trading_date = kb_pin80b.trading_date
)
LEFT JOIN
	kb_pin80b
ON
	kb_values.code = kb_pin80b.code,
	kb_values.trading_date = kb_pin80b.trading_date
)
WHERE DATE(`kb_values.trading_date`) = '2022-05-06'
;